[workspace]
resolver = "2"
members = [
    "dna/zomes/data/holon_space/holon",
    "dna/zomes/data/property",
    "dna/zomes/data/meta_space/descriptor",
    "dna/zomes/data/meta_space/exports",
    "dna/zomes/data/meta_space/mapping",
    "dna/zomes/data/meta_space/types",
    "dna/zomes/coordination/interface",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
