[workspace]
resolver = "2"
members = [
    "dna/zomes/integrity/holonspace/holon",
    "dna/zomes/integrity/metaspace/descriptor",
    "dna/zomes/integrity/metaspace/exports",
    "dna/zomes/integrity/metaspace/mapping",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
