[package]
name = "hc_zome_integrity_type_desc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "hc_zome_integrity_type_desc"

[dependencies]
hdk = { workspace = true }
hdi = { workspace = true}

serde = { workspace = true }

